# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180419_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.FileField(default='..img/default.jpg', upload_to='images/'),
        ),
    ]
